# TCL File Generated by Component Editor 21.1
# Thu Apr 16 20:53:25 EDT 2026
# DO NOT MODIFY


# 
# voxel_gpu "Voxel GPU" v1.0
# why am i alone :( 2026.04.16.20:53:25
# Hardware-accelerated quad rasterizer
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module voxel_gpu
# 
set_module_property DESCRIPTION "Hardware-accelerated quad rasterizer"
set_module_property NAME voxel_gpu
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "why am i alone :("
set_module_property DISPLAY_NAME "Voxel GPU"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_assignment embeddedsw.dts.vendor "csee4840"
set_module_assignment embeddedsw.dts.name "voxel_gpu"
set_module_assignment embeddedsw.dts.group "voxel"

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL voxel_gpu
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file voxel_gpu/rtl/voxel_gpu.sv SYSTEM_VERILOG PATH voxel_gpu/rtl/voxel_gpu.sv TOP_LEVEL_FILE
add_fileset_file voxel_gpu/rtl/voxel_raster_helpers.svh SYSTEM_VERILOG_INCLUDE PATH voxel_gpu/rtl/voxel_raster_helpers.svh
add_fileset_file voxel_gpu/rtl/voxel_color_helpers.svh SYSTEM_VERILOG_INCLUDE PATH voxel_gpu/rtl/voxel_color_helpers.svh
add_fileset_file voxel_gpu/rtl/voxel_math_utils.sv SYSTEM_VERILOG PATH voxel_gpu/rtl/voxel_math_utils.sv
add_fileset_file voxel_gpu/rtl/voxel_perf_counters.sv SYSTEM_VERILOG PATH voxel_gpu/rtl/voxel_perf_counters.sv
add_fileset_file voxel_gpu/rtl/voxel_sdp_ram.sv SYSTEM_VERILOG PATH voxel_gpu/rtl/voxel_sdp_ram.sv
add_fileset_file voxel_gpu/rtl/voxel_banked_sdp_ram.sv SYSTEM_VERILOG PATH voxel_gpu/rtl/voxel_banked_sdp_ram.sv
add_fileset_file voxel_gpu/rtl/voxel_texture_rom.sv SYSTEM_VERILOG PATH voxel_gpu/rtl/voxel_texture_rom.sv
add_fileset_file voxel_gpu/rtl/voxel_vga_counters.sv SYSTEM_VERILOG PATH voxel_gpu/rtl/voxel_vga_counters.sv
add_fileset_file voxel_gpu/assets/textures.mif MIF PATH voxel_gpu/assets/textures.mif
add_fileset_file voxel_gpu/assets/recip_lut.hex HEX PATH voxel_gpu/assets/recip_lut.hex
add_fileset_file sdram_local_test/Sdram_Control.v VERILOG PATH sdram_local_test/Sdram_Control.v
add_fileset_file sdram_local_test/control_interface.v VERILOG PATH sdram_local_test/control_interface.v
add_fileset_file sdram_local_test/command.v VERILOG PATH sdram_local_test/command.v
add_fileset_file sdram_local_test/sdr_data_path.v VERILOG PATH sdram_local_test/sdr_data_path.v
add_fileset_file sdram_local_test/Sdram_RD_FIFO.v VERILOG PATH sdram_local_test/Sdram_RD_FIFO.v
add_fileset_file sdram_local_test/Sdram_WR_FIFO.v VERILOG PATH sdram_local_test/Sdram_WR_FIFO.v
add_fileset_file sdram_local_test/sdram_pll0.v VERILOG PATH sdram_local_test/sdram_pll0.v
add_fileset_file sdram_local_test/sdram_pll0/sdram_pll0_0002.v VERILOG PATH sdram_local_test/sdram_pll0/sdram_pll0_0002.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 13
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 byteenable byteenable Input 4
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point vga
# 
add_interface vga conduit end
set_interface_property vga associatedClock clock
set_interface_property vga associatedReset ""
set_interface_property vga ENABLED true
set_interface_property vga EXPORT_OF ""
set_interface_property vga PORT_NAME_MAP ""
set_interface_property vga CMSIS_SVD_VARIABLES ""
set_interface_property vga SVD_ADDRESS_GROUP ""

add_interface_port vga VGA_B b Output 8
add_interface_port vga VGA_BLANK_n blank_n Output 1
add_interface_port vga VGA_CLK clk Output 1
add_interface_port vga VGA_G g Output 8
add_interface_port vga VGA_HS hs Output 1
add_interface_port vga VGA_R r Output 8
add_interface_port vga VGA_SYNC_n sync_n Output 1
add_interface_port vga VGA_VS vs Output 1


# 
# connection point voxel_sdram
# 
add_interface voxel_sdram conduit end
set_interface_property voxel_sdram associatedClock clock
set_interface_property voxel_sdram associatedReset ""
set_interface_property voxel_sdram ENABLED true
set_interface_property voxel_sdram EXPORT_OF ""
set_interface_property voxel_sdram PORT_NAME_MAP ""
set_interface_property voxel_sdram CMSIS_SVD_VARIABLES ""
set_interface_property voxel_sdram SVD_ADDRESS_GROUP ""

add_interface_port voxel_sdram DRAM_ADDR addr Output 13
add_interface_port voxel_sdram DRAM_BA ba Output 2
add_interface_port voxel_sdram DRAM_CAS_N cas_n Output 1
add_interface_port voxel_sdram DRAM_CKE cke Output 1
add_interface_port voxel_sdram DRAM_CLK dram_clk Output 1
add_interface_port voxel_sdram DRAM_CS_N cs_n Output 1
add_interface_port voxel_sdram DRAM_DQ dq Bidir 16
add_interface_port voxel_sdram DRAM_LDQM ldqm Output 1
add_interface_port voxel_sdram DRAM_RAS_N ras_n Output 1
add_interface_port voxel_sdram DRAM_UDQM udqm Output 1
add_interface_port voxel_sdram DRAM_WE_N we_n Output 1
