// Dual-read texture-atlas ROM. Each lane gets an explicit 1-cycle
// altsyncram ROM so pipe2_tex_addr at cycle T produces texel data at T+1,
// aligned with pipe2 -> draw_pipe metadata. Both ROM copies share the same
// .mif atlas generated by hw/voxel_gpu/scripts/generate_textures.py.
// ====================================================================
module voxel_texture_rom #(
    parameter int DATA_W = 8,
    parameter int ADDR_W = 15,
    parameter int DEPTH  = 32768,
    parameter      INIT_FILE = "voxel_gpu/assets/textures.mif"
) (
    input  logic                clk,
    input  logic [ADDR_W-1:0]   rd_addr,
    output logic [DATA_W-1:0]   rd_data,
    input  logic [ADDR_W-1:0]   rd_addr_b,
    output logic [DATA_W-1:0]   rd_data_b
);
    wire [DATA_W-1:0] q_a;
    wire [DATA_W-1:0] q_b;
    assign rd_data   = q_a;
    assign rd_data_b = q_b;

    // Lane 0 ROM.
    altsyncram altsyncram_rom_a (
        .address_a      (rd_addr),
        .clock0         (clk),
        .q_a            (q_a),
        .aclr0          (1'b0),
        .aclr1          (1'b0),
        .address_b      ({ADDR_W{1'b1}}),
        .addressstall_a (1'b0),
        .addressstall_b (1'b0),
        .byteena_a      (1'b1),
        .byteena_b      (1'b1),
        .clock1         (1'b1),
        .clocken0       (1'b1),
        .clocken1       (1'b1),
        .clocken2       (1'b1),
        .clocken3       (1'b1),
        .data_a         ({DATA_W{1'b0}}),
        .data_b         ({DATA_W{1'b0}}),
        .eccstatus      (),
        .q_b            (),
        .rden_a         (1'b1),
        .rden_b         (1'b1),
        .wren_a         (1'b0),
        .wren_b         (1'b0)
    );
    defparam
        altsyncram_rom_a.address_aclr_a = "NONE",
        altsyncram_rom_a.address_reg_a = "CLOCK0",
        altsyncram_rom_a.clock_enable_input_a = "BYPASS",
        altsyncram_rom_a.clock_enable_output_a = "BYPASS",
        altsyncram_rom_a.init_file = INIT_FILE,
        altsyncram_rom_a.intended_device_family = "Cyclone V",
        altsyncram_rom_a.lpm_hint = "ENABLE_RUNTIME_MOD=NO",
        altsyncram_rom_a.lpm_type = "altsyncram",
        altsyncram_rom_a.numwords_a = DEPTH,
        altsyncram_rom_a.operation_mode = "ROM",
        altsyncram_rom_a.outdata_aclr_a = "NONE",
        altsyncram_rom_a.outdata_reg_a = "UNREGISTERED",
        altsyncram_rom_a.ram_block_type = "M10K",
        altsyncram_rom_a.widthad_a = ADDR_W,
        altsyncram_rom_a.width_a = DATA_W,
        altsyncram_rom_a.width_byteena_a = 1;

    // Lane 1 ROM.
    altsyncram altsyncram_rom_b (
        .address_a      (rd_addr_b),
        .clock0         (clk),
        .q_a            (q_b),
        .aclr0          (1'b0),
        .aclr1          (1'b0),
        .address_b      ({ADDR_W{1'b1}}),
        .addressstall_a (1'b0),
        .addressstall_b (1'b0),
        .byteena_a      (1'b1),
        .byteena_b      (1'b1),
        .clock1         (1'b1),
        .clocken0       (1'b1),
        .clocken1       (1'b1),
        .clocken2       (1'b1),
        .clocken3       (1'b1),
        .data_a         ({DATA_W{1'b0}}),
        .data_b         ({DATA_W{1'b0}}),
        .eccstatus      (),
        .q_b            (),
        .rden_a         (1'b1),
        .rden_b         (1'b1),
        .wren_a         (1'b0),
        .wren_b         (1'b0)
    );
    defparam
        altsyncram_rom_b.address_aclr_a = "NONE",
        altsyncram_rom_b.address_reg_a = "CLOCK0",
        altsyncram_rom_b.clock_enable_input_a = "BYPASS",
        altsyncram_rom_b.clock_enable_output_a = "BYPASS",
        altsyncram_rom_b.init_file = INIT_FILE,
        altsyncram_rom_b.intended_device_family = "Cyclone V",
        altsyncram_rom_b.lpm_hint = "ENABLE_RUNTIME_MOD=NO",
        altsyncram_rom_b.lpm_type = "altsyncram",
        altsyncram_rom_b.numwords_a = DEPTH,
        altsyncram_rom_b.operation_mode = "ROM",
        altsyncram_rom_b.outdata_aclr_a = "NONE",
        altsyncram_rom_b.outdata_reg_a = "UNREGISTERED",
        altsyncram_rom_b.ram_block_type = "M10K",
        altsyncram_rom_b.widthad_a = ADDR_W,
        altsyncram_rom_b.width_a = DATA_W,
        altsyncram_rom_b.width_byteena_a = 1;

endmodule
